// dummy/stockList.js

const stockList = [
    { symbol: "RELIANCE", name: "Reliance Industries" },
    { symbol: "TCS", name: "Tata Consultancy Services" },
    { symbol: "INFY", name: "Infosys Ltd" },
    { symbol: "HDFCBANK", name: "HDFC Bank" },
    { symbol: "ICICIBANK", name: "ICICI Bank" },
    { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank" },
    { symbol: "LT", name: "Larsen & Toubro" },
    { symbol: "SBIN", name: "State Bank of India" },
    { symbol: "AXISBANK", name: "Axis Bank" },
    { symbol: "BAJFINANCE", name: "Bajaj Finance" },
    { symbol: "HINDUNILVR", name: "Hindustan Unilever" },
    { symbol: "ITC", name: "ITC Ltd" },
    { symbol: "HCLTECH", name: "HCL Technologies" },
    { symbol: "ASIANPAINT", name: "Asian Paints" },
    { symbol: "MARUTI", name: "Maruti Suzuki" },
    { symbol: "SUNPHARMA", name: "Sun Pharmaceutical" },
    { symbol: "TITAN", name: "Titan Company" },
    { symbol: "ULTRACEMCO", name: "UltraTech Cement" },
    { symbol: "WIPRO", name: "Wipro Ltd" },
    { symbol: "POWERGRID", name: "Power Grid Corporation" },
    { symbol: "BAJAJFINSV", name: "Bajaj Finserv" },
    { symbol: "NTPC", name: "NTPC Ltd" },
    { symbol: "TATAMOTORS", name: "Tata Motors" },
    { symbol: "NESTLEIND", name: "Nestle India" },
    { symbol: "JSWSTEEL", name: "JSW Steel" },
    { symbol: "TATASTEEL", name: "Tata Steel" },
    { symbol: "INDUSINDBK", name: "IndusInd Bank" },
    { symbol: "ADANIENT", name: "Adani Enterprises" },
    { symbol: "ADANIGREEN", name: "Adani Green Energy" },
    { symbol: "ADANIPORTS", name: "Adani Ports" },
    { symbol: "COALINDIA", name: "Coal India" },
    { symbol: "BRITANNIA", name: "Britannia Industries" },
    { symbol: "CIPLA", name: "Cipla Ltd" },
    { symbol: "DIVISLAB", name: "Divi's Laboratories" },
    { symbol: "EICHERMOT", name: "Eicher Motors" },
    { symbol: "HEROMOTOCO", name: "Hero MotoCorp" },
    { symbol: "BPCL", name: "Bharat Petroleum" },
    { symbol: "HDFCLIFE", name: "HDFC Life Insurance" },
    { symbol: "GRASIM", name: "Grasim Industries" },
    { symbol: "SHREECEM", name: "Shree Cement" },
    { symbol: "UPL", name: "UPL Ltd" },
    { symbol: "ONGC", name: "Oil and Natural Gas Corp" },
  ];
  
  export default stockList;
  